import Head from "next/head";
import React from "react";

const Layout: React.FC = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link
          rel="icon"
          href="https://icons.iconarchive.com/icons/icons8/windows-8/256/Cinema-Captain-America-icon.png"
        />
      </Head>

      <main>{children}</main>
    </>
  );
};

export default Layout;
