import Head from "next/head";
import Image from "next/image";
// importa o hook useRouter
import { useRouter } from "next/router";

export default function PostIdItem() {
  // import o router onde é possivel tratar parametros que foi passado na rota
  const router = useRouter();
  // id param
  const { id } = router.query;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{`Id Param page ${id}`}</h1>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
